services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: phoenix_pass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./scripts/postgres:/docker-entrypoint-initdb.d:ro
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  phoenix:
    image: arizephoenix/phoenix:version-11.6.2
    depends_on:
      - postgres
    ports:
      - "6006:6006"  # Phoenix UI
      - "6007:4317"  # OTLP gRPC receiver
    environment:
      - PHOENIX_SQL_DATABASE_URL=postgresql://postgres:phoenix_pass@postgres:5432/phoenix
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6006/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: